Feature/task alb
LauPerlaza/Ducks-web-page pull request #2
Opened 2023-10-24 18:58 UTC by LauPerlaza

2023-10-24 19:05 UTC, danielrive requested changes
revisar comments

2023-10-24 19:05 UTC, danielrive commented on main.tf
> +  health_check_path = "/var/www/html"
el path no esta bien aqui, este path es donde nginx o apache va a buscar los arvhicos pero para el usuariio es transparente, uno desde el navegador no ve esto
puede ir / o algun otro path que se haya configurado dentro del servidor

2023-10-24 19:05 UTC, danielrive commented on main.tf
> +  ingress {
faltaria el CIDR block o grupo de seguridad donde se va a permitir los request, el origen

2023-10-24 19:12 UTC, LauPerlaza commented on main.tf
> +  ingress {
como seria eso?

2023-10-24 19:17 UTC, danielrive commented on main.tf
> +  ingress {
asi como se hizo en los otros security groups que creaste

2023-10-25 00:02 UTC, LauPerlaza commented on main.tf
> +  ingress {
y que hiria ahi??

2023-10-25 06:12 UTC, danielrive commented on main.tf
> +  ingress {
el origen de los request, desde donde se van a permitir las conexiones

2023-10-25 14:07 UTC, LauPerlaza commented on main.tf
> +  ingress {
no te entiendo

2023-10-26 14:20 UTC, danielrive approved these changes

2023-10-26 14:21 UTC, danielrive approved these changes

2023-10-26 14:26 UTC, danielrive approved these changes

2023-10-26 14:40 UTC, merged